FORMAT: 1A

# (Free)RADIUS user and group management API

(Free)RADIUS user and group management API.

# Group Users

Resources related to RADIUS user management.

## User Collection [/api/v1/services/radius/users]

### List All Users [GET]

+ Response 200 (application/json)

        [

        ]
