FORMAT: 1A

# (Free)RADIUS user and group management API

(Free)RADIUS user and group management API.

# Group Users

Resources related to RADIUS user management.

## User Collection [/api/v1/services/radius/users]

### List All Users [GET]

The "check" and "reply" properties are lists of RADIUS Check and Reply attributes according the
RADIUS specification ([RFC2865](https://tools.ietf.org/html/rfc2865)),
as well as
[internal ones](https://github.com/vasilakisfil/secure_file_transfer/blob/46b95a88150e5e9605786ff9301d5259af1a28ab/config/radius-dictionary#L145).

+ Response 200 (application/json)

        [
            {
                "user": {
                    "name": "__user_test",
                    "check": [
                        {
                            "Id": 197,
                            "User-Name": "__user_test",
                            "Attribute": "User-Name",
                            "Operator": ":=",
                            "Value": "__user_test"
                        },
                        {
                            "Id": 199,
                            "User-Name": "__user_test",
                            "Attribute": "SSHA1-Password",
                            "Operator": ":=",
                            "Value": "SQaMuG003/CnO1uVEUafF87kr0PBW04gV+1Em+G/+bJ3Sj472o58uw=="
                        },
                        {
                            "Id": 200,
                            "User-Name": "__user_test",
                            "Attribute": "Auth-Type",
                            "Operator": ":=",
                            "Value": "Reject"
                        },
                        {
                            "Id": 201,
                            "User-Name": "__user_test",
                            "Attribute": "Login-Time",
                            "Operator": ":=",
                            "Value": "Wk2305-0855,Sa,Su2305-1655"
                        }
                    ],
                    "reply": [
                        {
                            "Id": 30,
                            "User-Name": "__user_test",
                            "Attribute": "Reply-Message",
                            "Operator": ":=",
                            "Value": "my reply msg"
                        },
                        {
                            "Id": 31,
                            "User-Name": "__user_test",
                            "Attribute": "Session-Timeout",
                            "Operator": ":=",
                            "Value": "7200"
                        },
                        {
                            "Id": 32,
                            "User-Name": "__user_test",
                            "Attribute": "Idle-Timeout",
                            "Operator": ":=",
                            "Value": "1800"
                        },
                        {
                            "Id": 33,
                            "User-Name": "__user_test",
                            "Attribute": "WISPr-Bandwidth-Max-Down",
                            "Operator": ":=",
                            "Value": "500000"
                        },
                        {
                            "Id": 34,
                            "User-Name": "__user_test",
                            "Attribute": "WISPr-Bandwidth-Max-Up",
                            "Operator": ":=",
                            "Value": "250000"
                        }
                    ],
                    "groups": [

                    ],
                    "personal": {
                        "Id": 2,
                        "User-Name": "__user_test",
                        "First-Name": "George",
                        "Last-Name": "Boole",
                        "Email": "george.boole@ucc.ie",
                        "Work-Phone": null,
                        "Home-Phone": null,
                        "Mobile-Phone": null,
                        "Address": null,
                        "City": null,
                        "State": null,
                        "Country": null,
                        "Postal-Code": null,
                        "Notes": null,
                        "Creation-Date": "2019-04-18 18:10:02 +0000",
                        "Update-Date": null,
                        "Birth-Date": "1815-11-02",
                        "Birth-City": null,
                        "Birth-State": null,
                        "ID-Code": null,
                        "Attachments": []
                    },
                    "accepted_terms": null
                }
            }
        ]

### Create a New User [POST]

+ Attributes (object)
    + check (object) - Requested RADIUS check attributes
        + User-name (string)
        + Password-Type (string) - "SSHA1-Password", "Cleartest-Password", etc.
        + User-Password (string)
    + reply (object) - Requested RADIUS reply attributes
    + confirm (object)
        + check (object)
            + User-Password(string) 

+ Request (application/json)

        {
            'check' => {
                'User-Name' => "__user_test",
                'Password-Type' => "SSHA1-Password",
                'User-Password'=> "pass"
            },
            'confirm' => {
                'check' => {
                    'User-Password' => "pass"
                }
            }
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/v1/services/radius/users/__user_test

    + Body

            {
                "total_items": 2,
                "page": 1,
                "per_page": 10,
                "users": [
                    {
                        "name": "u1",
                        "check": [
                            {
                                "Id": 1,
                                "User-Name": "u1",
                                "Attribute": "User-Name",
                                "Operator": ":=",
                                "Value": "u1"
                            },
                            {
                                "Id": 16,
                                "User-Name": "u1",
                                "Attribute": "SSHA1-Password",
                                "Operator": ":=",
                                "Value": "Yg+Zkt25hotWV4vLYXcEjGZv153BmsHJMilz0+XT15W5J4S78ieoZQ=="
                            },
                            {
                                "Id": 18,
                                "User-Name": "u1",
                                "Attribute": "Login-Time",
                                "Operator": ":=",
                                "Value": "Wk2305-0855,Sa,Su2305-1655"
                            }
                        ],
                    "reply": [
                        {
                            "Id": 6,
                            "User-Name": "u1",
                            "Attribute": "Reply-Message",
                            "Operator": ":=",
                            "Value": "my reply msg"
                        },
                        {
                            "Id": 7,
                            "User-Name": "u1",
                            "Attribute": "Session-Timeout",
                            "Operator": ":=",
                            "Value": "7200"
                        },
                        {
                            "Id": 8,
                            "User-Name": "u1",
                            "Attribute": "Idle-Timeout",
                            "Operator": ":=",
                            "Value": "1800"
                        },
                        {
                            "Id": 9,
                            "User-Name": "u1",
                            "Attribute": "WISPr-Bandwidth-Max-Down",
                            "Operator": ":=",
                            "Value": "800000"
                        },
                        {
                            "Id": 10,
                            "User-Name": "u1",
                            "Attribute": "WISPr-Bandwidth-Max-Up",
                            "Operator": ":=",
                            "Value": "400000"
                        },
                        {
                            "Id": 110,
                            "User-Name": "u1",
                            "Attribute": "Fall-Through",
                            "Operator": "=",
                            "Value": "yes"
                        }
                    ],
                    "groups": [

                    ],
                    "personal": null,
                    "accepted_terms": null
                    },
                    {
                    "name": "__user_test",
                    "check": [
                        {
                            "Id": 24,
                            "User-Name": "__user_test",
                            "Attribute": "User-Name",
                            "Operator": ":=",
                            "Value": "__user_test"
                        },
                        {
                            "Id": 25,
                            "User-Name": "__user_test",
                            "Attribute": "SSHA1-Password",
                            "Operator": ":=",
                            "Value": "tVFZM9ZIlWFTJKA1ZL8g5OdOyWW1B/nrQ1Uuhnlkr2eF1DLc/VbpEw=="
                        }
                    ],
                    "reply": [

                    ],
                    "groups": [

                    ],
                    "personal": null,
                    "accepted_terms": null
                    }
                ]
            }
