#!/usr/bin/env ruby

# Restore IP addresses on an OpenVPN TAP device
#
# ENVIRONMENT: (from openvpn --setenv)
#
# RUBYLIB 
#   prepend to the standard Ruby $LOAD_PATH 
#
# NETWORK_INTERFACES_DATFILE
#   marshal dump of the saved interfaces state
#
#
# COMMAND LINE ARGUMENTS:
#
# ARGV[0] (from openvpn --up)
#   interface name
#
#
# EXAMPLE:
#   
# RUBYLIB=/home/onboard/onboard/lib NETWORK_INTERFACES_DATFILE=/home/onboard/onboard/etc/config/network/interfaces.dat ./up ovpn_tap0

require 'pp'

require 'onboard/network/interface'

ifname = ARGV[0]

all_interfaces = OnBoard::Network::Interface.getAll

all_interfaces_saved = Marshal.load File.read ENV['NETWORK_INTERFACES_DATFILE']

# Arrays of one element (for compatibility)
netifs = all_interfaces.select{|x| x.name == ifname}
netifs_saved = all_interfaces_saved.select{|x| x.name == ifname}

OnBoard::Network::Interface.restore(
  :saved_interfaces => netifs_saved,
  :current_interfaces => netifs 
)


